- name: setup redis server
  hosts: redis
  become: yes
  tasks:
  - name: Disale default redis
    ansible.builtin.command: dnf module disable redis -y

    # there is no disable module so we use this command module

  - name: enable redis 7
    ansible.builtin.command: dnf module enable redis:7 -y

  - name: Install redis 
    ansible.builtin.package:
      name: redis 
      state: present

  - name: allowing remote connections
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: disable protected module
    ansible.builtin.lineinfile:
      path: /etc/redis/redis.conf
      regexp: 'protected-mode'
      line: 'protected-mode no'

  - name: start and enable redis
    ansible.builtin.service:
      name: redis 
      state: started
      enabled: yes